### ISSUE TITLE
English for Kids

### ISSUE THREAD

**Issue by KrohNic** [marinamarine/rsschool-cv#3]
Привет, есть проблема с твоим English for Kids.
У меня открывается пустая страница в консоли пишет:
Uncaught TypeError: Failed to execute 'insertAdjacentElement' on 'Element': parameter 2 is not of type 'Element'.
Пиши в дискорд или mikolka.del@gmail.com, будем разбираться)

**Comment by marinamarine** [comment]
Привет! Спасибо большое за сообщение! Писала тебе в личку в дискорде, но там не понятно, прочитано или нет. Задеплоила заново, посмотри пожалуйста, если есть возможность:)

> Привет, есть проблема с твоим English for Kids.
> У меня открывается пустая страница в консоли пишет:
> Uncaught TypeError: Failed to execute 'insertAdjacentElement' on 'Element': parameter 2 is not of type 'Element'.
> Пиши в дискорд или [mikolka.del@gmail.com](mailto:mikolka.del@gmail.com), будем разбираться)
